[package]
name = "rift-receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = "0.12"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
display-info = "0.5.7"
